migration:
  initial:
    file:
      credits: /migration/initial/credits.csv
      movies: /migration/initial/movies.csv
spring:
  main:
    web-environment: false
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elastic-local
      #properties:
      repositories.enabled: true 